services:
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s

  app:
    image: ghcr.io/karzdy760/app-lab:ci-4
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      DB_HOST: db
      DB_NAME: appdb
      DB_USER: labapp
      DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_VERSION: "1.0"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
